name: forks_and_spoons
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  outline_material_icons: 0.1.1
  flutter_swiper: 1.1.6
  cupertino_icons: 0.1.2
  http: 0.12.1

  # Huawei Mobile Services
  huawei_analytics: ^5.1.0+300
  huawei_account: 5.2.0+300
  agconnect_crash: ^1.2.0+201
  huawei_push: 5.1.1+301
  huawei_map: ^5.0.3+302
  huawei_location: ^5.0.0+301

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/menu/
   - assets/carousel/
